version: '3'

services:
  sso-server:
    container_name: sso-server
    restart: always
    build: ./server
    tty: true
    ports:
      - "80:80"
      - "443:443"
      - "8022:22"
    volumes:
      - ./server/media:/data/sso/media
